<?php

namespace Iapps\RemittanceService\Common;

class CacheKey{

    const REMITTANCE_RECIPIENT_LIST = 'REMITTANCE_RECIPIENT_LIST';
    const REMITTANCE_RECIPIENT_DETAIL = 'REMITTANCE_RECIPIENT_DETAIL';
    const RECIPIENT_ID = 'REMITTANCE.RECIPIENT_ID';
    const RECIPIENT_RECIPIENT_USER_PROFILE_ID = 'REMITTANCE.RECIPIENT_RECIPIENT_USER_PROFILE_ID';
    const RECIPIENT_ATTRIBUTE_RECIPIENT_ID = 'REMITTANCE.RECIPIENT_ATTRIBUTE_RECIPIENT_ID';
    const REMITTANCE_COMPANY_LIST = 'REMITTANCE_COMPANY_LIST';
    const REMITTANCE_COMPANY_ID = 'REMITTANCE_COMPANY_ID';
    const REMITTANCE_COMPANY_SERVICE_PROVIDER_ID = 'REMITTANCE_COMPANY_SERVICE_PROVIDER_ID';
    const REMITTANCE_COMPANY_CODE = 'REMITTANCE_COMPANY_CODE';
	
    const REMITTANCE_COMPANY_USER_CUSTOMERID = 'REMITTANCE_COMPANY_USER_CUSTOMERID';
    
	const REMITTANCE_RECIPIENT_COLLECTION_INFO_RECIPIENTID = 'REMITTANCE_RECIPIENT_COLLECTION_INFO_RECIPIENTID';

    const REMITTANCE_SERVICE_ID = 'REMITTANCE_SERVICE_ID';
    const REMITTANCE_SERVICE_LIST = 'REMITTANCE_SERVICE_LIST';
    const REMITTANCE_SERVICE_FROM_TO = 'REMITTANCE_SERVICE_LIST_FROM_TO';

    const REMITTANCE_CONFIG_ID = 'REMITTANCE_CONFIG_ID';
    const REMITTANCE_CONFIG_ALL = 'REMITTANCE_CONFIG_ALL';

    const REMITTANCE_CORPORATE_SERVICE_ID = 'REMITTANCE_CORPORATE_SERVICE_ID';

    const REMITTANCE_MESSAGE_COMMON_ID = 'REMITTANCE_MESSAGE_COMMON_ID';
    const REMITTANCE_MESSAGE_COMMON_CODE_LANG = 'REMITTANCE_MESSAGE_COMMON_CODE_LANG';

    const REMITTANCE_PROFIT_SHARING_CORPORATE_ID = 'REMITTANCE_PROFIT_SHARING_CORPORATE_ID';

    const REMITTANCE_PAYMENT_MODE_CORPORATE_SERVICE_ID = 'REMITTANCE_PAYMENT_MODE_CORPORATE_SERVICE_ID';
    //due to there are different set of entity of the same table!! out of control!
    const REMITTANCE_PAYMENT_MODE_CORPORATE_SERVICE_ID2 = 'REMITTANCE.PAYMENT_MODE_CORPORATE_SERVICE_ID2';

    const REMITTANCE_PAYMENT_MODE_FEE_GROUP_ACTIVE_PAYMENT_MODE_ID = 'REMITTANCE_PAYMENT_MODE_FEE_GROUP_ACTIVE_PAYMENT_MODE_ID';
    const REMITTANCE_PAYMENT_MODE_FEE_FEE_GROUP_ID = 'REMITTANCE_PAYMENT_MODE_FEE_FEE_GROUP_ID';
    const LAST_APPROVED_PAYMENT_MODE_FEE_GROUP_CORPORATE_SERVICE_ID = 'REMITTANCE.LAST_PAYMENT_MODE_FEE_GROUP_PAYMENT_MODE_ID';
    
    const REMITTANCE_COMPANY_RECIPIENT_RECIPIENT_ID = 'REMITTANCE_COMPANY_RECIPIENT_RECIPIENT_ID';
    const REMITTANCE_COMPANY_RECIPIENT_RECIPIENT_ID_COMPANY_ID = 'REMITTANCE_COMPANY_RECIPIENT_RECIPIENT_ID_COMPANY_ID';
    
    const USER_REMITTANCE_LIST_USER_PROFILE_ID_INTERNATIONAL_LIMIT_PAGE = 'REMITTANCE.USER_REMITTANCE_LIST_USER_PROFILE_ID_INTERNATIONAL_LIMIT_PAGE.USER_REMITTANCE_LIST_USER_PROFILE_ID_INTERNATIONAL_LIMIT_10_PAGE_1';
    
    const PAYMENT_MODE_COST_PAYMENT_MODE_GROUP_ID = 'REMITTANCE.PAYMENT_MODE_COST_PAYMENT_MODE_GROUP_ID';    
}