<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>
        Modern
    </title>
    <style>
    .tb_header{
        text-align:center;
        vertical-align: bottom;  font-size: 9pt;
        border:1px #000 solid;
    }
    </style>
</head>

<body style="margin: 0; padding: 0; background: #ffffff;" bgcolor="#ffffff">

    <div align="center" style="font-size: 20px;">
        FROM <?php echo $result['partner_name'];?>
        <br>
        FUNDS REMITTED SUMMARY
    </div>

    <div>&nbsp;</div>
    <div>Beneficiary Outside Singapore         From : <?php echo ($result['start_time'].' To: '. $result['end_time']);?></div>
    <div>&nbsp;</div>

    <table align="center" border="1" width="900px" style="font-size:8px;">
          <tr style="background-color:#ABA8A8">
            <td style="width:450px">Funds Remitted Through</td>           
            <td style="width:450px">Amount(SGD)</td>
          </tr>          
       
          <tr>
              <td style="width:450px">To Country Partner Company</td>                
              <td style="width:450px"><?php echo $result['to_country_partner_company'];?></td>
          </tr>   

          <tr>   
              <td style="width:450px">Foreign Agent</td>
              <td style="width:450px"><?php echo $result['foreign_agent'];?></td>
          </tr>     

          <tr>   
              <td style="width:450px">Local Remittance Licensee</td>
              <td style="width:450px"> - </td>
          </tr>     

          <tr>   
              <td style="width:450px">GRAND TOTAL:</td>
              <td style="width:450px"><?php echo $result['to_country_partner_company'] + $result['foreign_agent'];?></td>
          </tr>      
                  
      </table>

    <div>&nbsp;</div>
    <div>&nbsp;</div>
    <div>Generated by SLIDE System on : <?php echo date('d/m/Y h:i:s a', time());?></div>

</body>

</html>
