<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>
        Modern
    </title>
    <style>
    .tb_header{
        text-align:center;
        vertical-align: bottom;  font-size: 9pt;
        border:1px #000 solid;
    }
    </style>
</head>

<body style="margin: 0; padding: 0; background: #ffffff;" bgcolor="#ffffff">

    <div align="center" style="font-size: 20px;">
        STATEMENT OF REMITTANCE
        <br>
        TRANSACTIONS FOR THE PERIOD ENDED
    </div>

    <div>&nbsp;</div>
    <div>From : <?php echo ($result['start_time'].' To: '. $result['end_time']);?></div>
    <div>&nbsp;</div>

    <table align="center" border="1" width="900px" style="font-size:8px;">
          <tr>
            <td style="width:450px">Total Volume of Remittance Transactions</td>           
            <td style="width:450px"><?php echo $result['total_of_remittance_trx'];?></td>
          </tr>          
       
          <tr>
              <td style="width:450px">Foreign Exchange Gain / Loss</td>                
              <td style="width:450px"><?php echo $result['foreign_exchange_gain'] .' / '. $result['foreign_exchange_loss'];?></td>
          </tr>   

          <tr>   
              <td style="width:450px">Commission and Fees</td>
              <td style="width:450px"><?php echo $result['commission'] .' / '.$result['fees'];?></td>
          </tr>     

          <tr>   
              <td style="width:450px">Max Outstanding on TT / MT</td>
              <td style="width:450px"><?php echo $result['max_outstanding_tt'] .' / '.$result['max_outstanding_mt'];?></td>
          </tr>     

          <tr>   
              <td style="width:450px">Number of Customer (Outward)</td>
              <td style="width:450px"><?php echo $result['number_of_customer_out'];?></td>
          </tr>      
        
          <tr>   
              <td style="width:450px">Number of Customer (Inward)</td>
              <td style="width:450px"><?php echo $result['number_of_customer_in'];?></td>
          </tr>     


          <tr>
              <td style="width:450px">Total</td>                
              <td style="width:450px"><?php echo $result['total_of_remittance_trx'] + $result['foreign_exchange_gain'] + $result['foreign_exchange_loss'] + $result['commission'] + $result['fees'] + $result['max_outstanding_tt'] + $result['max_outstanding_mt'] + $result['number_of_customer_out'] + $result['number_of_customer_in'];?></td>
          </tr>   
      </table>

    <div>&nbsp;</div>
    <div>&nbsp;</div>
    <div>Generated by SLIDE System on : <?php echo date('d/m/Y h:i:s a', time());?></div>

</body>

</html>
